# Generated by Django 4.2.7 on 2024-01-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
                ('id_empresa', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('actividad_comercial', models.CharField(max_length=200)),
                ('ced_rep_legal', models.CharField(max_length=10)),
                ('nom_rep_legal', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('redes', models.CharField(max_length=1000)),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='UsuarioPersona',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
                ('id_persona', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='RelacionOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacion_hija', to='api.usuarioempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacion_padre', to='api.usuarioempresa')),
            ],
        ),
    ]
