# Generated by Django 4.2.7 on 2023-11-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id_archivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=200)),
                ('telfono', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('actividad_comercial', models.CharField(max_length=200)),
                ('ced_rep_legal', models.CharField(max_length=10)),
                ('nom_rep_legal', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('redes', models.CharField(max_length=1000)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRecoleccion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptada'), ('C', 'Cancelada'), ('F', 'Finalizada'), ('E', 'En proceso')], max_length=1)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_asig', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recolector')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RolesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReportesDenuncias',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resolucion', models.CharField(max_length=1000)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('id_usuario_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_hijo', to='api.usuarioempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_padre', to='api.usuarioempresa')),
            ],
        ),
        migrations.AddField(
            model_name='recolector',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='recolector',
            name='id_usuario_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuariopersona'),
        ),
        migrations.CreateModel(
            name='CarnetRecolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archivos')),
                ('id_recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recolector')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('observacion', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField()),
                ('id_recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recolector')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archivos')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitudrecoleccion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archivos')),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportesdenuncias')),
            ],
        ),
    ]
