# Generated by Django 4.2.7 on 2024-01-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_hija', to='api.usuarioempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_padre', to='api.usuarioempresa')),
            ],
        ),
        migrations.DeleteModel(
            name='RelacionOrganizacion',
        ),
    ]
