# Generated by Django 4.2.7 on 2024-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="url_foto",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
