# Generated by Django 4.2.7 on 2024-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_usuario_url_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciclador",
            name="estado_reciclador",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo"), ("E", "Espera")],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reciclador",
            name="id_empresa",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="url_foto",
            field=models.URLField(blank=True, null=True),
        ),
    ]
