# Generated by Django 4.2.7 on 2024-01-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_relacionempresa_delete_relacionorganizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciclador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reciclador', models.CharField(max_length=13, unique=True)),
                ('calificacion', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarioempresa')),
            ],
        ),
    ]
