# Generated by Django 4.2.7 on 2024-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_reciclador_estado_reciclador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarioempresa",
            name="redes",
            field=models.JSONField(default=dict),
        ),
    ]
