# Generated by Django 4.2.7 on 2024-01-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_archivo_solicitudrecoleccion_reportedenuncias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='tu_valor_predeterminado', max_length=128),
        ),
    ]
