# Generated by Django 4.2.7 on 2024-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_usuariopersona_cedula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Territorio",
            fields=[
                (
                    "id_territorio",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("id_nivel_territorial", models.IntegerField()),
                ("id_territorio_padre", models.IntegerField()),
                ("descripcion", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "urm_territorios",
            },
        ),
    ]
