# Generated by Django 4.2.7 on 2024-04-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_territorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioempresa",
            name="ruc",
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
