# Generated by Django 4.2.7 on 2024-01-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclador',
            name='id_empresa',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
