# Generated by Django 4.2.7 on 2024-04-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciclador",
            name="estado_reciclador",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo"), ("E", "Espera")],
                default="E",
                max_length=1,
            ),
        ),
    ]
