# Generated by Django 4.2.7 on 2024-01-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reciclador_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecoleccion',
            name='id_reciclador',
            field=models.CharField(max_length=13),
        ),
    ]
