# Generated by Django 4.2.7 on 2024-05-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_reciclador_estado_reciclador"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMaterial",
            fields=[
                (
                    "id_tipo_material",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Activo"), ("I", "Inactivo")],
                        default="A",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroReciclaje",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Activo"), ("I", "Inactivo")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "id_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tipomaterial",
                    ),
                ),
                (
                    "id_reciclador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reciclador"
                    ),
                ),
                (
                    "id_usuario_ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_ingreso",
                        to="api.usuario",
                    ),
                ),
                (
                    "id_usuario_modificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_modificacion",
                        to="api.usuario",
                    ),
                ),
            ],
        ),
    ]
