# Generated by Django 4.2.7 on 2024-07-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_carruselfoto_quienessomos_seccion_timeline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carruselfoto",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="parrafo",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="pasostimeline",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="quienessomos",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
            ),
        ),
    ]
