# Generated by Django 4.2.7 on 2024-07-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_carruselfoto_estado_alter_parrafo_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroAcopio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_acopio", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("referencia", models.TextField()),
                ("imageURL", models.URLField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_acopio",
                        to="api.usuarioempresa",
                    ),
                ),
            ],
        ),
    ]
