# Generated by Django 4.2.7 on 2024-07-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_centroacopio"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudDetalle",
            fields=[
                (
                    "id_solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.solicitudrecoleccion",
                    ),
                ),
                (
                    "materiales",
                    models.TextField(
                        help_text="Lista de materiales separados por comas"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        help_text="Dirección del solicitante", max_length=255
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Latitud y longitud separadas por coma",
                        max_length=255,
                    ),
                ),
                ("calificado", models.BooleanField(default=False)),
                (
                    "fotos",
                    models.ManyToManyField(
                        blank=True, related_name="solicitudes", to="api.imagen"
                    ),
                ),
            ],
        ),
    ]
