# Generated by Django 4.2.7 on 2024-07-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_solicituddetalle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centroacopio",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="centroacopio",
            name="lon",
        ),
        migrations.AddField(
            model_name="centroacopio",
            name="ubicacion",
            field=models.CharField(
                default=[0, 0],
                help_text="Latitud y longitud separadas por coma",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
