# Generated by Django 4.2.7 on 2024-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_centroacopio_ubicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicituddetalle",
            name="ubicacion",
            field=models.JSONField(
                help_text="Ubicación como lista [latitud, longitud]"
            ),
        ),
    ]
