# Generated by Django 4.2.7 on 2024-08-18 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_solicituddetalle_ubicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudRechazada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_rechazo",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "id_reciclador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechazos_realizados",
                        to="api.reciclador",
                    ),
                ),
                (
                    "id_solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechazos",
                        to="api.solicitudrecoleccion",
                    ),
                ),
            ],
        ),
    ]
