# Generated by Django 4.2.7 on 2024-09-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_solicitudrecoleccion_fecha_arribo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calificacion",
            old_name="calificacion_reciclador",
            new_name="calificacion",
        ),
        migrations.RemoveField(
            model_name="calificacion",
            name="id_reciclador",
        ),
        migrations.RemoveField(
            model_name="calificacion",
            name="id_usuario",
        ),
        migrations.RemoveField(
            model_name="calificacion",
            name="observacion",
        ),
        migrations.AddField(
            model_name="calificacion",
            name="id_solicitud",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.solicitudrecoleccion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calificacion",
            name="id_usuario_calificado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_calificado",
                to="api.usuariopersona",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calificacion",
            name="id_usuario_calificador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_calificador",
                to="api.usuariopersona",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calificacion",
            name="motivo",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solicitudrecoleccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("P", "Pendiente"),
                    ("A", "Aceptada"),
                    ("L", "Cerca"),
                    ("C", "Cancelada"),
                    ("F", "Fallida"),
                    ("E", "Entregada"),
                    ("R", "Recolectada"),
                ],
                max_length=1,
            ),
        ),
    ]
