# Generated by Django 4.2.7 on 2024-09-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0023_rename_calificacion_reciclador_calificacion_calificacion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudesCanceladas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=500)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "id_solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.solicitudrecoleccion",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_cancela",
                        to="api.usuariopersona",
                    ),
                ),
            ],
        ),
    ]
