# Generated by Django 4.2.7 on 2024-09-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_solicitudrecoleccion_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calificacion",
            name="motivo",
        ),
    ]
