# Generated by Django 4.2.7 on 2024-09-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_remove_calificacion_motivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="id_usuario_calificado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_calificado",
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="id_usuario_calificador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_calificador",
                to="api.usuario",
            ),
        ),
    ]
