# Generated by Django 4.2.7 on 2024-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_solicitudescanceladas_id_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioTemporal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=200, unique=True)),
                ("clave", models.CharField(max_length=128)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("empresa", "Empresa"),
                            ("persona", "Persona"),
                            ("reciclador", "Reciclador"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
