# Generated by Django 4.2.7 on 2024-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_usuariotemporal"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariotemporal",
            name="datos_adicionales",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
