# Generated by Django 4.2.7 on 2024-09-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_usuariotemporal_datos_adicionales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centroacopio",
            name="imageURL",
        ),
    ]
