# Generated by Django 4.2.7 on 2024-09-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_parrafo_imageurl_alter_seccion_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeline",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
