# Generated by Django 4.2.7 on 2024-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_timeline_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="centroacopio",
            name="fotos",
            field=models.ManyToManyField(
                blank=True, related_name="centros_acopio", to="api.imagen"
            ),
        ),
        migrations.AddField(
            model_name="centroacopio",
            name="informacion",
            field=models.CharField(
                blank=True,
                help_text="Información adicional sobre el centro de acopio",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="centroacopio",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
