# Generated by Django 4.2.7 on 2024-11-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_centroacopio_fotos_centroacopio_informacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centroacopio",
            old_name="id",
            new_name="id_centro",
        ),
    ]
