# Generated by Django 4.2.7 on 2024-11-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_rename_id_centroacopio_id_centro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centroacopio",
            name="organizacion",
        ),
    ]
