# Generated by Django 4.2.7 on 2024-11-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_centroacopio_organizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="centroacopio",
            name="organizacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centros_acopio",
                to="api.usuarioempresa",
            ),
            preserve_default=False,
        ),
    ]
