# Generated by Django 4.2.7 on 2024-11-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_alter_centroacopio_id_centro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CentroAcopio",
        ),
    ]
