# Generated by Django 4.2.7 on 2024-11-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_delete_centroacopio"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroAcopio",
            fields=[
                ("id_centro", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_acopio", models.CharField(max_length=100)),
                (
                    "ubicacion",
                    models.JSONField(
                        help_text="Ubicación como lista [latitud, longitud]"
                    ),
                ),
                ("referencia", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Activo"), ("I", "Inactivo")], max_length=10
                    ),
                ),
                (
                    "informacion",
                    models.CharField(
                        blank=True,
                        help_text="Información adicional sobre el centro de acopio",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fotos",
                    models.ManyToManyField(
                        blank=True, related_name="centros_acopio", to="api.imagen"
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_acopio",
                        to="api.usuarioempresa",
                    ),
                ),
            ],
        ),
    ]
