# Generated by Django 4.2.7 on 2024-11-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_centroacopio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centroacopio",
            name="fotos",
            field=models.ManyToManyField(
                blank=True, related_name="centros_acopio_imagen", to="api.imagen"
            ),
        ),
    ]
